name: MNE-BIDS

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  create:
    branches: [master]
    tags: ['**']

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # python-version: [3.5, 3.6, 3.7, 3.8]

    env:
      TZ: Europe/Berlin
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 12
    - name: Set up Miniconda Python environment
      uses: goanpeca/setup-miniconda@v1.4.1
      with:
        environment-file: environment.yml
        activate-environment: mne_bids
        auto-update-conda: true
        channel-priority: strict
        channels: conda-forge, defaults
    - name: Install mne-python
      shell: bash -l {0}
      run: |
        pip uninstall --yes mne-python
        git clone --depth 1 https://github.com/mne-tools/mne-python.git
        pip install --no-deps -e ./mne-python

    - name: Install BIDS validator
      run: npm install -g bids-validator
    - name: Display versions and environment information
      shell: bash -l {0}
      run: |
        echo $TZ
        date
        npm --version
        node --version
        python --version
        which python
        mne sys_info
        bids-validator --version
    - name: Install MNE-BIDS
      shell: bash -l {0}
      run: pip install --no-deps .
    - name: Run pytest
      shell: bash -l {0}
      run: pytest . --cov=./mne_bids --cov-report=xml --verbose --ignore mne-python
    - name: Run style & documentation tests
      shell: bash -l {0}
      run: make pep
    - name: Upload coverage stats to codecov
      run: bash <(curl -s https://codecov.io/bash)
