name: MNE-BIDS

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  create:
    branches: [master]
    tags: ['**']

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        # os: [ubuntu-latest, macos-latest]
        os: [macos-latest]
        python-version: [3.8]

    env:
      TZ: Europe/Berlin
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 12
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    # - name: Set up Miniconda Python environment
    #   uses: goanpeca/setup-miniconda@v1.4.1
    #   with:
    #     environment-file: environment.yml
    #     activate-environment: mne_bids
    #     auto-update-conda: true
    #     channel-priority: strict
    #     channels: conda-forge, defaults
    - name: Install dependencies using pip
      run: |
        python -m pip install --upgrade pip
        python --version
        which python
        which pip
        pip install -r requirements.txt
    - name: Install latest mne-python
      shell: bash -l {0}
      run: |
        pip install -U https://github.com/mne-tools/mne-python/archive/master.zip
    - name: Install BIDS validator
      run: npm install -g bids-validator
    - name: Display versions and environment information
      shell: bash -l {0}
      run: |
        echo $TZ
        date
        npm --version
        node --version
        python --version
        which python
        mne sys_info
        bids-validator --version
    - name: Install MNE-BIDS
      shell: bash -l {0}
      run: pip install --no-deps .
    - name: Run pytest
      shell: bash -l {0}
      run: pytest . --cov=./mne_bids --cov-report=xml --verbose --ignore mne-python
    - name: Run style & documentation tests
      shell: bash -l {0}
      run: make pep
    - name: Upload coverage stats to codecov
      run: bash <(curl -s https://codecov.io/bash)
