name: build

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  create:
    branches: [master]
    tags: ['**']

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        # os: [ubuntu-latest, macos-latest]
        os: [ubuntu-latest]
        python-version: [3.8]
        validator-version: [stable, master]

    env:
      TZ: Europe/Berlin
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 12
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies using pip
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        git clone --depth 1 https://github.com/mne-tools/mne-python.git
        pip install --no-deps -e ./mne-python
    - name: Install BIDS validator (stable)
      if: "matrix.validator-version == 'stable'"
      run: npm install -g bids-validator
    - name: Install BIDS validator (master)
      if: "matrix.validator-version == 'master'"
      run: |
        git clone --depth 1 https://github.com/bids-standard/bids-validator
        cd bids-validator
        git checkout master
        yarn
        cd ..
        export PATH=$PWD/bids-validator/bin:$PATH
    - name: Display versions and environment information
      run: |
        echo $TZ
        date
        npm --version
        node --version
        python --version
        which python
        mne sys_info
        bids-validator --version
    - name: Install MNE-BIDS
      run: pip install --no-deps .
    - name: Run pytest
      run: pytest . --cov=./mne_bids --cov-report=xml --verbose --ignore mne-python
    - name: Run style & documentation tests
      if: "matrix.os == 'ubuntu-latest'"
      run: make pep
    - name: Upload coverage stats to codecov
      if: "matrix.os == 'ubuntu-latest'"
      run: bash <(curl -s https://codecov.io/bash)
