name: build

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  create:
    branches: [master]
    tags: ['**']

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        # os: [ubuntu-latest, macos-latest]
        # os: [ubuntu-latest]
        os: [windows-latest]
        python-version: [3.8]
        # validator-version: [stable, master]
        # validator-version: [master]
        validator-version: [stable]
        # mne-version: [maint/0.19, maint/0.20, master]
        # exclude:
        #   - os: macos-latest
        #     validator-version: master
        #   - os: windows-latest
        #     validator-version: master

    env:
      TZ: Europe/Berlin
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 12
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies using pip
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        git clone --depth 1 https://github.com/mne-tools/mne-python.git
        pip install --no-deps -e ./mne-python
    - name: Install BIDS validator (stable)
      shell: bash
      if: "matrix.validator-version == 'stable'"
      run: |
        rm -rf node_modules
        npm install -g npm@latest
        npm install -g core-util-is
        npm install -g bids-validator
    - name: Install BIDS validator (master)
      shell: bash
      if: "matrix.validator-version == 'master'"
      run: |
        cd ..
        git clone --depth 1 https://github.com/bids-standard/bids-validator
        cd bids-validator
        git checkout master
        yarn
        echo "::add-path::$(pwd)/bids-validator/bin"
        cd ../mne-bids
    - name: Display versions and environment information
      shell: bash
      run: |
        echo $TZ
        date
        echo "npm"; npm --version
        echo "node"; node --version
        echo "bids-validator"; bids-validator --version
        python --version
        which python
        mne sys_info
    - name: Install MNE-BIDS
      shell: bash
      run: pip install --no-deps .
    - name: Run pytest
      shell: bash
      run: |
        echo "bids-validator"; bids-validator --version
        which bids-validator
        pytest . --cov=./mne_bids --cov-report=xml --verbose --ignore mne-python -k test_set
    - name: Run style & documentation tests
      if: "matrix.os == 'ubuntu-latest'"
      run: make pep
    - name: Upload coverage stats to codecov
      if: "matrix.os == 'ubuntu-latest'"
      run: bash <(curl -s https://codecov.io/bash)
